services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123#"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network
    ports:
      - "1433:1433"

  postgres:
    build: .
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  sqlserver-data:

networks:
  app-network:
    driver: bridge
